name: Paul Rigby
favicon: null
layout_spectrum: 0.5647184781264514
typography_spectrum: 0.8072933054063469
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#9D2D3C'
    - '#DDE4DD'
    - '#BCAB47'
    - '#6B574B'
    - '#160600'
  brandStrength: 0.44069761992432177
  lightness: 0.8463320492301136
  saturation: 0.4283322400879115
  rhythmicContrast: 0.013151353225111961
purpose: []
